import * as Icons from './components/icons.jsx'

export const apps = {
  '1Password 7': Icons.OnePassword,
  'Affinity Designer': Icons.AffinityDesigner,
  'Affinity Photo': Icons.AffinityPhoto,
  'Affinity Publisher': Icons.AffinityPublisher,
  Airmail: Icons.Airmail,
  Alacritty: Icons.Terminal,
  Alfred: Icons.Alfred,
  'Android Messages': Icons.AndroidMessages,
  'App Store': Icons.AppStore,
  Audacity: Icons.Audacity,
  Bitwarden: Icons.BitWarden,
  Blender: Icons.Blender,
  Bear: Icons.Bear,
  'Brave Browser': Icons.BraveBrowser,
  Calendar: Icons.Calendar,
  'Canary Mail': Icons.Mail,
  Caprine: Icons.Caprine,
  Chromium: Icons.GoogleChrome,
  ClickUp: Icons.ClickUp,
  Code: Icons.Code,
  VSCodium: Icons.VSCodium,
  Default: Icons.Default,
  Discord: Icons.Discord,
  'Discord Canary': Icons.Discord,
  'Discord PTB': Icons.Discord,
  Drafts: Icons.Drafts,
  Dropbox: Icons.Dropbox,
  'Microsoft Excel': Icons.MicrosoftExcel,
  FaceTime: Icons.FaceTime,
  Finder: Icons.Finder,
  Figma: Icons.Figma,
  'Firefox Developer Edition': Icons.FirefoxDeveloperEdition,
  'Firefox Nightly': Icons.FirefoxDeveloperEdition,
  Firefox: Icons.Firefox,
  'GitHub Desktop': Icons.GitHub,
  'Google Chrome': Icons.GoogleChrome,
  'Google Chrome Canary': Icons.GoogleChrome,
  Grammarly: Icons.Grammarly,
  Hyper: Icons.Terminal,
  iTerm2: Icons.Terminal,
  Insomnia: Icons.Insomnia,
  'Keyboard Maestro': Icons.KeyboardMaestro,
  Keynote: Icons.Keynote,
  kitty: Icons.Terminal,
  Linear: Icons.Linear,
  Mail: Icons.Mail,
  Mailspring: Icons.Mail,
  MAMP: Icons.Mamp,
  'MAMP PRO': Icons.Mamp,
  Mattermost: Icons.Mattermost,
  Messages: Icons.Messages,
  'Microsoft Edge': Icons.MicrosoftEdge,
  'Microsoft To Do': Icons.Things,
  Music: Icons.Music,
  Notes: Icons.Notes,
  Notion: Icons.Notion,
  Obsidian: Icons.Obsidian,
  OBS: Icons.OBSStudio,
  MacVim: Icons.Vim,
  Nova: Icons.Nova,
  Numbers: Icons.Numbers,
  Pages: Icons.Pages,
  Podcasts: Icons.Podcasts,
  'Microsoft PowerPoint': Icons.MicrosoftPowerPoint,
  Reminders: Icons.Reminders,
  Safari: Icons.Safari,
  'Safari Technology Preview': Icons.Safari,
  'Sequel Ace': Icons.SequelAce,
  'Sequel Pro': Icons.SequelPro,
  Sketch: Icons.Sketch,
  Skype: Icons.Skype,
  Slack: Icons.Slack,
  Spark: Icons.Spark,
  Spotify: Icons.Spotify,
  Spotlight: Icons.Spotlight,
  'Sublime Text': Icons.SublimeText,
  Telegram: Icons.Telegram,
  Terminal: Icons.Terminal,
  Things: Icons.Things,
  Transmit: Icons.Transmit,
  Tweetbot: Icons.Twitter,
  Twitter: Icons.Twitter,
  Vim: Icons.Vim,
  VimR: Icons.Vim,
  VLC: Icons.VLC,
  'VMware Fusion': Icons.VMwareFusion,
  WhatsApp: Icons.WhatsApp,
  'Microsoft Word': Icons.MicrosoftWord,
  Zeplin: Icons.Zeplin,
  'zoom.us': Icons.Zoom,
  'League of Legends': Icons.LeagueOfLegends,
  WebStorm: Icons.WebStorm,
  'IntelliJ IDEA': Icons.Idea,
  'Android Studio': Icons.AndroidStudio,
  Thunderbird: Icons.Thunderbird,
  qutebrowser: Icons.QuteBrowser,
  Emacs: Icons.Emacs,
  Pine: Icons.Pine,
  Min: Icons.MinBrowser,
  Reeder: Icons.Reeder5,
  Joplin: Icons.Joplin,
  Notability: Icons.Notability,
  Skim: Icons.PDF,
  WezTerm: Icons.Terminal,
  'Color Picker': Icons.ColorPicker,

  // German app names
  Nachrichten: Icons.Messages,

  // Chinese app names
  访达: Icons.Finder,
  邮件: Icons.Mail,
  微信: Icons.Wechat,
  网易云音乐: Icons.NeteaseMusic
}
