import {
  AndroidMessagesIcon,
  CalendarIcon,
  CaprineIcon,
  CodeIcon,
  DefaultIcon,
  DiscordIcon,
  FigmaIcon,
  FirefoxIcon,
  GoogleChromeIcon,
  MailIcon,
  MessagesIcon,
  MusicIcon,
  NotesIcon,
  OnePasswordIcon,
  RemindersIcon,
  SafariIcon,
  SequelProIcon,
  SkypeIcon,
  SlackIcon,
  SparkIcon,
  SpotifyIcon,
  TerminalIcon,
  ZeplinIcon
} from './components/Icons.jsx'

export const appIcons = {
  '1Password 7': OnePasswordIcon,
  'Android Messages': AndroidMessagesIcon,
  Calendar: CalendarIcon,
  Caprine: CaprineIcon,
  Code: CodeIcon,
  Default: DefaultIcon,
  Discord: DiscordIcon,
  Figma: FigmaIcon,
  Firefox: FirefoxIcon,
  'Google Chrome': GoogleChromeIcon,
  iTerm2: TerminalIcon,
  Terminal: TerminalIcon,
  Mail: MailIcon,
  Messages: MessagesIcon,
  Music: MusicIcon,
  Notes: NotesIcon,
  Reminders: RemindersIcon,
  Safari: SafariIcon,
  'Sequel Pro': SequelProIcon,
  Skype: SkypeIcon,
  Slack: SlackIcon,
  Spark: SparkIcon,
  Spotify: SpotifyIcon,
  Zeplin: ZeplinIcon
}
