import {
  ActivityMonitorIcon,
  BearIcon,
  InkscapeIcon,
  PreviewIcon,
  PyCharmIcon,
  QuickTimeIcon,
  qutebrowserIcon,
  ReederIcon,
  SignalIcon,
  SystemPreferencesIcon,
  TeamsIcon,
  YousicianIcon,
  ZoteroIcon,
  AffinityDesignerIcon,
  AffinityPhotoIcon,
  AffinityPublisherIcon,
  AirmailIcon,
  AlfredIcon,
  AndroidMessagesIcon,
  AppStoreIcon,
  BitWardenIcon,
  BlenderIcon,
  BraveBrowserIcon,
  CalendarIcon,
  CaprineIcon,
  CodeIcon,
  DefaultIcon,
  DiscordIcon,
  DropboxIcon,
  FigmaIcon,
  FirefoxDeveloperEditionIcon,
  FinderIcon,
  FirefoxIcon,
  GitHubIcon,
  GoogleChromeIcon,
  GrammarlyIcon,
  KeynoteIcon,
  MailIcon,
  MampIcon,
  MessagesIcon,
  MicrosoftEdgeIcon,
  MicrosoftExcelIcon,
  MicrosoftPowerPointIcon,
  MicrosoftWordIcon,
  MusicIcon,
  NotesIcon,
  NotionIcon,
  NovaIcon,
  NumbersIcon,
  OnePasswordIcon,
  PagesIcon,
  RemindersIcon,
  SafariIcon,
  SequelAceIcon,
  SequelProIcon,
  SketchIcon,
  SkypeIcon,
  SlackIcon,
  SparkIcon,
  SpotifyIcon,
  SpotlightIcon,
  TelegramIcon,
  TerminalIcon,
  ThingsIcon,
  TransmitIcon,
  TwitterIcon,
  VLCIcon,
  VMwareFusionIcon,
  WhatsAppIcon,
  ZeplinIcon,
  ZoomIcon
} from './components/Icons.jsx'

export const appIcons = {
  'Activity Monitor': ActivityMonitorIcon,
  Bear: BearIcon,
  Inkscape: InkscapeIcon,
  'Microsoft Teams': TeamsIcon,
  Preview: PreviewIcon,
  PyCharm: PyCharmIcon,
  'QuickTime Player': QuickTimeIcon,
  'System Preferences': SystemPreferencesIcon,
  qutebrowser: qutebrowserIcon,
  Reeder: ReederIcon,
  Signal: SignalIcon,
  Yousician: YousicianIcon,
  Zotero: ZoteroIcon,
  '1Password 7': OnePasswordIcon,
  'Affinity Designer': AffinityDesignerIcon,
  'Affinity Photo': AffinityPhotoIcon,
  'Affinity Publisher': AffinityPublisherIcon,
  Airmail: AirmailIcon,
  Alacritty: TerminalIcon,
  Alfred: AlfredIcon,
  'Android Messages': AndroidMessagesIcon,
  'App Store': AppStoreIcon,
  Bitwarden: BitWardenIcon,
  Blender: BlenderIcon,
  'Brave Browser': BraveBrowserIcon,
  Calendar: CalendarIcon,
  Caprine: CaprineIcon,
  Code: CodeIcon,
  Default: DefaultIcon,
  Discord: DiscordIcon,
  Dropbox: DropboxIcon,
  'Microsoft Excel': MicrosoftExcelIcon,
  Finder: FinderIcon,
  Figma: FigmaIcon,
  'Firefox Developer Edition': FirefoxDeveloperEditionIcon,
  Firefox: FirefoxIcon,
  'GitHub Desktop': GitHubIcon,
  'Google Chrome': GoogleChromeIcon,
  Grammarly: GrammarlyIcon,
  Hyper: TerminalIcon,
  iTerm2: TerminalIcon,
  Keynote: KeynoteIcon,
  kitty: TerminalIcon,
  Mail: MailIcon,
  Mailspring: MailIcon,
  MAMP: MampIcon,
  'MAMP PRO': MampIcon,
  Messages: MessagesIcon,
  'Microsoft Edge': MicrosoftEdgeIcon,
  'Microsoft To Do': ThingsIcon,
  Music: MusicIcon,
  Notes: NotesIcon,
  Notion: NotionIcon,
  Nova: NovaIcon,
  Numbers: NumbersIcon,
  Pages: PagesIcon,
  'Microsoft PowerPoint': MicrosoftPowerPointIcon,
  Reminders: RemindersIcon,
  Safari: SafariIcon,
  'Sequel Ace': SequelAceIcon,
  'Sequel Pro': SequelProIcon,
  Sketch: SketchIcon,
  Skype: SkypeIcon,
  Slack: SlackIcon,
  Spark: SparkIcon,
  Spotify: SpotifyIcon,
  Spotlight: SpotlightIcon,
  Telegram: TelegramIcon,
  Terminal: TerminalIcon,
  Things: ThingsIcon,
  Transmit: TransmitIcon,
  Tweetbot: TwitterIcon,
  Twitter: TwitterIcon,
  VLC: VLCIcon,
  'VMware Fusion': VMwareFusionIcon,
  WhatsApp: WhatsAppIcon,
  'Microsoft Word': MicrosoftWordIcon,
  Zeplin: ZeplinIcon,
  'zoom.us': ZoomIcon
}
